//! Path-traced renderer.
//!
//! Cornell Box megakernel path tracer (NEE + MIS). Each frame runs three
//! passes:
//!
//! 1. **path-trace** — fragment shader samples one new path per pixel and
//!    writes four AOV color attachments (radiance / albedo / normal /
//!    depth) into a set of sample textures.
//! 2. **accumulate** — ping-pong: blend the four sample textures into the
//!    previous accumulator with `weight = 1 / (frame + 1)`, writing the
//!    new accumulator into the four target views.
//! 3. **present** — tone-map the radiance AOV to the surface (Reinhard +
//!    gamma).
//!
//! Sampler choice (PCG / Halton / Sobol) is selected at runtime via
//! [`State::set_sampler`] — the WGSL shader dispatches on a single
//! `sampler_kind` uniform field. CPU sampler implementations + tests
//! live in [`sampler`].
//!
//! The [`gpu`](crate::gpu) module supplies the wgpu instance factory and
//! the `OrbitCamera`. The rasterized pipeline ([`raster`](crate::raster))
//! shares nothing with this code below the `gpu` seam.

pub mod bvh;
pub mod cloud;
pub mod dielectric;
pub mod ggx;
pub mod grid;
pub mod integrator;
pub mod medium;
pub mod mesh;
pub mod phase;
pub mod sampler;
pub mod scene;

#[cfg(not(target_arch = "wasm32"))]
pub mod env;

#[cfg(not(target_arch = "wasm32"))]
pub mod denoise;

#[cfg(not(target_arch = "wasm32"))]
pub mod converge;

#[cfg(not(target_arch = "wasm32"))]
pub mod metrics;

#[cfg(not(target_arch = "wasm32"))]
pub mod offscreen;

#[cfg(not(target_arch = "wasm32"))]
pub mod output;

#[cfg(target_arch = "wasm32")]
pub mod web;

use bytemuck::{Pod, Zeroable};

use crate::gpu::OrbitCamera;
use crate::pathtrace::integrator::IntegratorKind;
use crate::pathtrace::mesh::TriangleScene;
use crate::pathtrace::sampler::SamplerKind;

/// Default Cornell Box, embedded at build time. The path tracer no
/// longer synthesises a scene inline — `State::new` and
/// `offscreen::render_offscreen` deserialize this glTF into a
/// [`TriangleScene`] on startup. The file is regenerated by
/// `cargo run --example gen_cornell`.
pub(crate) const CORNELL_QUADS_GLTF: &[u8] = include_bytes!("../data/gltf/cornell_quads.gltf");

/// Loads the embedded Cornell Box default scene. Panics on parse
/// failure — the file is checked into the repo and exercised by
/// `tests/cornell_gltf.rs`, so failure here would indicate the loader
/// regressed against a known-good fixture.
pub fn default_triangle_scene() -> TriangleScene {
    crate::pathtrace::mesh::load_glb_bytes(CORNELL_QUADS_GLTF)
        .expect("embedded cornell_quads.gltf must parse cleanly")
}

/// HDR storage for AOV accumulation. Filterable, broadly supported, and
/// enough precision for the Cornell Box convergence story.
pub const HDR_FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba16Float;

/// AOV slot indices. Order matches the WGSL `PathTraceOut` /
/// `AccumOut` `@location(...)` attributes and the `Targets` arrays.
pub const AOV_RADIANCE: usize = 0;
pub const AOV_ALBEDO: usize = 1;
pub const AOV_NORMAL: usize = 2;
pub const AOV_DEPTH: usize = 3;
pub const NUM_AOVS: usize = 4;

/// Small uniform for the accumulate pass. 16 bytes — must match WGSL `AccumU`.
#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
pub(crate) struct AccumUniform {
    pub frame_count: u32,
    pub _pad: [u32; 3],
}

/// Per-resolution render targets and their bind groups.
///
/// `sample_views` are the path-trace outputs; `accum_views[ping]` holds
/// the running average. `accumulate_bg[ping]` reads from
/// `accum_views[ping]` (the previous accumulator) and is bound when
/// writing into `accum_views[1 - ping]`. The optional `present_bg` only
/// exists for the windowed renderer; the offscreen renderer skips it.
pub(crate) struct Targets {
    pub sample_views: [wgpu::TextureView; NUM_AOVS],
    pub accum_views: [[wgpu::TextureView; NUM_AOVS]; 2],
    pub accumulate_bg: [wgpu::BindGroup; 2],
    pub present_bg: [wgpu::BindGroup; 2],
}

/// The path-tracer renderer: owns the surface, pipelines, and scene state.
///
/// The triangle scene's storage buffers (vertex / index / material /
/// triangle-material / emissive-triangle) are owned here so the bind
/// group stays valid for the lifetime of the renderer; they're not
/// resized or rebuilt on `resize`.
pub struct State {
    surface: wgpu::Surface<'static>,
    device: wgpu::Device,
    queue: wgpu::Queue,
    config: wgpu::SurfaceConfiguration,

    pathtrace_pipeline: wgpu::RenderPipeline,
    accumulate_pipeline: wgpu::RenderPipeline,
    present_pipeline: wgpu::RenderPipeline,

    accumulate_bgl: wgpu::BindGroupLayout,
    present_bgl: wgpu::BindGroupLayout,

    uniform_buf: wgpu::Buffer,
    accum_uniform_buf: wgpu::Buffer,
    pathtrace_bg: wgpu::BindGroup,

    // Scene storage buffers — held to extend their lifetime past the
    // bind group's internal Arc references.
    _vertex_buf: wgpu::Buffer,
    _index_buf: wgpu::Buffer,
    _material_buf: wgpu::Buffer,
    _triangle_material_buf: wgpu::Buffer,
    _emissive_triangle_buf: wgpu::Buffer,
    _bvh_nodes_buf: wgpu::Buffer,
    _bvh_tri_indices_buf: wgpu::Buffer,
    _textures: wgpu::Texture,
    _sampler: wgpu::Sampler,
    _cloud_grid: wgpu::Texture,
    _cloud_grid_sampler: wgpu::Sampler,
    _env_texture: wgpu::Texture,
    _env_sampler: wgpu::Sampler,
    _env_data: wgpu::Buffer,

    targets: Targets,

    uniforms: scene::Uniforms,
    pub camera: OrbitCamera,
    pub frame_count: u32,
    read_idx: usize,
}

/// Creates one HDR render-attachment texture and returns its default
/// view. `extra_usage` lets callers add `COPY_SRC` for AOV readback.
pub(crate) fn create_hdr_texture(
    device: &wgpu::Device,
    w: u32,
    h: u32,
    label: &str,
    extra_usage: wgpu::TextureUsages,
) -> (wgpu::Texture, wgpu::TextureView) {
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some(label),
        size: wgpu::Extent3d {
            width: w.max(1),
            height: h.max(1),
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: HDR_FORMAT,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT
            | wgpu::TextureUsages::TEXTURE_BINDING
            | extra_usage,
        view_formats: &[],
    });
    let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
    (tex, view)
}

fn make_aov_views(
    device: &wgpu::Device,
    w: u32,
    h: u32,
    prefix: &str,
) -> [wgpu::TextureView; NUM_AOVS] {
    let names = ["radiance", "albedo", "normal", "depth"];
    std::array::from_fn(|i| {
        let (_tex, view) = create_hdr_texture(
            device,
            w,
            h,
            &format!("{prefix}-{}", names[i]),
            wgpu::TextureUsages::empty(),
        );
        view
    })
}

fn build_targets(
    device: &wgpu::Device,
    w: u32,
    h: u32,
    accumulate_bgl: &wgpu::BindGroupLayout,
    present_bgl: &wgpu::BindGroupLayout,
    accum_uniform_buf: &wgpu::Buffer,
) -> Targets {
    let sample_views = make_aov_views(device, w, h, "sample");
    let accum_views = [
        make_aov_views(device, w, h, "accum0"),
        make_aov_views(device, w, h, "accum1"),
    ];

    let make_accumulate_bg = |prev: usize| {
        let mut entries: Vec<wgpu::BindGroupEntry> = Vec::with_capacity(1 + NUM_AOVS * 2);
        entries.push(wgpu::BindGroupEntry {
            binding: 0,
            resource: accum_uniform_buf.as_entire_binding(),
        });
        for (i, view) in sample_views.iter().enumerate() {
            entries.push(wgpu::BindGroupEntry {
                binding: 1 + i as u32,
                resource: wgpu::BindingResource::TextureView(view),
            });
        }
        for (i, view) in accum_views[prev].iter().enumerate() {
            entries.push(wgpu::BindGroupEntry {
                binding: 1 + (NUM_AOVS + i) as u32,
                resource: wgpu::BindingResource::TextureView(view),
            });
        }
        device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("accumulate-bg"),
            layout: accumulate_bgl,
            entries: &entries,
        })
    };

    let make_present_bg = |idx: usize| {
        device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("present-bg"),
            layout: present_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&accum_views[idx][AOV_RADIANCE]),
            }],
        })
    };

    Targets {
        accumulate_bg: [make_accumulate_bg(0), make_accumulate_bg(1)],
        present_bg: [make_present_bg(0), make_present_bg(1)],
        sample_views,
        accum_views,
    }
}

/// Layout for the path-trace pass: one uniform + seven read-only
/// storage buffers (vertices, tri_indices, materials, tri_materials,
/// emissive_triangles, bvh_nodes, bvh_tri_indices) + one texture array
/// + one sampler. Shared between the windowed and offscreen renderers.
pub(crate) fn build_pathtrace_bgl(device: &wgpu::Device) -> wgpu::BindGroupLayout {
    let storage = |binding: u32| wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Storage { read_only: true },
            has_dynamic_offset: false,
            min_binding_size: None,
        },
        count: None,
    };
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("pathtrace-bgl"),
        entries: &[
            wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Uniform,
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            },
            storage(1),
            storage(2),
            storage(3),
            storage(4),
            storage(5),
            storage(6),
            storage(7),
            // PT-textures: base-color texture array + linear-repeat
            // sampler. `Rgba8UnormSrgb` so an embedded gamma-encoded
            // image (the typical baseColorTexture) decodes to linear.
            wgpu::BindGroupLayoutEntry {
                binding: 8,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Texture {
                    sample_type: wgpu::TextureSampleType::Float { filterable: true },
                    view_dimension: wgpu::TextureViewDimension::D2Array,
                    multisampled: false,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 9,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                count: None,
            },
            // PT-vdb: 3-D density texture + clamp-to-edge linear sampler.
            // `R8Unorm` so the trilinear sample lands in `[0, 1]` directly.
            // Empty scenes get a 1×1×1 zero texture as fallback.
            wgpu::BindGroupLayoutEntry {
                binding: 10,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Texture {
                    sample_type: wgpu::TextureSampleType::Float { filterable: true },
                    view_dimension: wgpu::TextureViewDimension::D3,
                    multisampled: false,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 11,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                count: None,
            },
            // PT-env: equirectangular HDR environment map + clamp-to-edge
            // linear sampler. `Rgba16Float` so radiance > 1 survives the
            // texture roundtrip cleanly (sky HDRs commonly have suns at
            // 10–1000×). Empty scenes get a 1×1 black pixel and the
            // `has_environment` uniform flag gates reads.
            wgpu::BindGroupLayoutEntry {
                binding: 12,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Texture {
                    sample_type: wgpu::TextureSampleType::Float { filterable: true },
                    view_dimension: wgpu::TextureViewDimension::D2,
                    multisampled: false,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 13,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering),
                count: None,
            },
            // PT-env: marginal + conditional CDF/PDF tables packed into
            // one storage buffer. Layout doc lives on `build_env_storage`.
            storage(14),
        ],
    })
}

/// Bundle of GPU buffers + textures backing a [`TriangleScene`]. Held
/// by both the windowed and offscreen renderers so their bind group
/// references stay live.
pub(crate) struct SceneBuffers {
    pub uniform: wgpu::Buffer,
    pub vertex: wgpu::Buffer,
    pub index: wgpu::Buffer,
    pub material: wgpu::Buffer,
    pub triangle_material: wgpu::Buffer,
    pub emissive_triangle: wgpu::Buffer,
    pub bvh_nodes: wgpu::Buffer,
    pub bvh_tri_indices: wgpu::Buffer,
    /// `texture_2d_array<f32>` carrying every glTF baseColorTexture.
    /// Always has at least one layer — a 1×1 white pixel when the
    /// scene has no textures — so the bind group is well-formed.
    pub textures: wgpu::Texture,
    pub textures_view: wgpu::TextureView,
    pub sampler: wgpu::Sampler,
    /// PT-vdb: 3-D density texture for cloud volumes. Always present;
    /// a 1×1×1 zero texture stands in when no cloud grid is loaded.
    pub cloud_grid: wgpu::Texture,
    pub cloud_grid_view: wgpu::TextureView,
    pub cloud_grid_sampler: wgpu::Sampler,
    /// PT-env: equirectangular HDR environment map. Always present;
    /// a 1×1 black pixel stands in when no env is set, and the
    /// integrator's `has_environment` uniform flag gates whether to
    /// read it at all.
    pub env_texture: wgpu::Texture,
    pub env_view: wgpu::TextureView,
    pub env_sampler: wgpu::Sampler,
    /// Importance-sampling tables for the env map. Always present;
    /// a stub buffer with a single 1.0 entry stands in when no env
    /// is set. Layout is documented on `build_env_storage`.
    pub env_data: wgpu::Buffer,
    /// PT-light-vs-env (plan 0020): unnormalised total emitted
    /// power of the environment map. Used as a uniform field so
    /// the WGSL Bernoulli pick can derive `p_env`. 0 when no
    /// env is bound.
    pub env_total_power: f32,
}

fn make_storage_buffer(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    data: &[u8],
    label: &str,
) -> wgpu::Buffer {
    // Storage buffer size must be ≥ the bound element's std430
    // stride. PT-many-lights introduced `array<EmissiveLight>`
    // with stride 16 — empty scenes (no emissive triangles)
    // need a 16-byte zero pad rather than 4 bytes so the bind
    // group validates. Other storage buffers with smaller
    // strides (u32 → 4) are still satisfied.
    const EMPTY_PAD: [u8; 16] = [0; 16];
    let bytes: &[u8] = if data.is_empty() { &EMPTY_PAD } else { data };
    let buf = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some(label),
        size: bytes.len() as u64,
        usage: wgpu::BufferUsages::STORAGE | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    queue.write_buffer(&buf, 0, bytes);
    buf
}

/// Uploads a [`TriangleScene`] into GPU storage buffers + an empty
/// uniform buffer (callers fill the uniform per frame).
pub(crate) fn build_scene_buffers(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    scene_data: &TriangleScene,
) -> SceneBuffers {
    build_scene_buffers_full(
        device,
        queue,
        scene_data,
        crate::pathtrace::grid::from_bytes_or_empty(CUMULUS_QVG),
        None,
    )
}

/// Same as `build_scene_buffers`, but using a caller-supplied
/// `Grid3D` instead of the embedded cumulus. Used by `render
/// --cloud-grid PATH` to pick a runtime-loaded grid.
#[cfg(not(target_arch = "wasm32"))]
pub(crate) fn build_scene_buffers_with_grid(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    scene_data: &TriangleScene,
    cloud_grid_data: crate::pathtrace::grid::Grid3D,
) -> SceneBuffers {
    build_scene_buffers_full(device, queue, scene_data, cloud_grid_data, None)
}

/// Full builder taking both an optional cloud grid and an optional
/// environment map. PT-env's CLI flag `--env-map PATH` ends up here.
#[cfg(not(target_arch = "wasm32"))]
pub(crate) fn build_scene_buffers_with_grid_and_env(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    scene_data: &TriangleScene,
    cloud_grid_data: crate::pathtrace::grid::Grid3D,
    env_map: Option<crate::pathtrace::env::EnvironmentMap>,
) -> SceneBuffers {
    build_scene_buffers_full(device, queue, scene_data, cloud_grid_data, env_map)
}

#[cfg(target_arch = "wasm32")]
type WebEnv = ();

fn build_scene_buffers_full(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    scene_data: &TriangleScene,
    cloud_grid_data: crate::pathtrace::grid::Grid3D,
    #[cfg(not(target_arch = "wasm32"))] env_map: Option<crate::pathtrace::env::EnvironmentMap>,
    #[cfg(target_arch = "wasm32")] _env_map: Option<WebEnv>,
) -> SceneBuffers {
    let uniform = device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("pathtrace-uniforms"),
        size: std::mem::size_of::<scene::Uniforms>() as u64,
        usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    });
    let vertex = make_storage_buffer(
        device,
        queue,
        bytemuck::cast_slice(&scene_data.vertices),
        "vertices",
    );
    let index = make_storage_buffer(
        device,
        queue,
        bytemuck::cast_slice(&scene_data.indices),
        "tri-indices",
    );
    let material = make_storage_buffer(
        device,
        queue,
        bytemuck::cast_slice(&scene_data.materials),
        "materials",
    );
    let triangle_material = make_storage_buffer(
        device,
        queue,
        bytemuck::cast_slice(&scene_data.triangle_materials),
        "tri-materials",
    );
    let emissive_triangle = make_storage_buffer(
        device,
        queue,
        bytemuck::cast_slice(&scene_data.emissive_lights),
        "emissive-triangles",
    );
    let bvh_nodes = make_storage_buffer(
        device,
        queue,
        bytemuck::cast_slice(&scene_data.bvh.nodes),
        "bvh-nodes",
    );
    let bvh_tri_indices = make_storage_buffer(
        device,
        queue,
        bytemuck::cast_slice(&scene_data.bvh.triangle_indices),
        "bvh-tri-indices",
    );
    let (textures, textures_view, sampler) =
        build_texture_array(device, queue, &scene_data.textures);
    let (cloud_grid, cloud_grid_view, cloud_grid_sampler) =
        build_cloud_grid_texture_from(device, queue, cloud_grid_data);
    #[cfg(not(target_arch = "wasm32"))]
    let (env_texture, env_view, env_sampler, env_data, env_total_power) =
        build_environment_resources(device, queue, env_map.as_ref());
    #[cfg(target_arch = "wasm32")]
    let (env_texture, env_view, env_sampler, env_data, env_total_power) =
        build_environment_resources_empty(device, queue);
    SceneBuffers {
        uniform,
        vertex,
        index,
        material,
        triangle_material,
        emissive_triangle,
        bvh_nodes,
        bvh_tri_indices,
        textures,
        textures_view,
        sampler,
        cloud_grid,
        cloud_grid_view,
        cloud_grid_sampler,
        env_texture,
        env_view,
        env_sampler,
        env_data,
        env_total_power,
    }
}

/// PT-env: assembles the env texture + sampler + importance-sampling
/// data buffer. When `env_map` is `None`, returns a 1×1 black pixel
/// + a stub data buffer so the bind group still validates.
///
/// The WGSL integrator reads the `has_environment` uniform flag and
/// skips env contributions entirely in that case.
#[cfg(not(target_arch = "wasm32"))]
fn build_environment_resources(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    env_map: Option<&crate::pathtrace::env::EnvironmentMap>,
) -> (
    wgpu::Texture,
    wgpu::TextureView,
    wgpu::Sampler,
    wgpu::Buffer,
    f32,
) {
    use crate::pathtrace::env::{EnvironmentMap, ImportanceTables};
    let stub = EnvironmentMap::new(1, 1, vec![[0.0, 0.0, 0.0]]);
    let env = env_map.unwrap_or(&stub);
    let w = env.width;
    let h = env.height;
    // Texture upload: Rgba16Float (4 × f16 per pixel).
    let rgba16: Vec<u16> = env
        .pixels
        .iter()
        .flat_map(|p| {
            [
                half::f16::from_f32(p[0]).to_bits(),
                half::f16::from_f32(p[1]).to_bits(),
                half::f16::from_f32(p[2]).to_bits(),
                half::f16::from_f32(1.0).to_bits(),
            ]
        })
        .collect();
    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("pathtrace-env-texture"),
        size: wgpu::Extent3d {
            width: w,
            height: h,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba16Float,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    queue.write_texture(
        wgpu::TexelCopyTextureInfo {
            texture: &texture,
            mip_level: 0,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        bytemuck::cast_slice(&rgba16),
        wgpu::TexelCopyBufferLayout {
            offset: 0,
            bytes_per_row: Some(w * 8),
            rows_per_image: Some(h),
        },
        wgpu::Extent3d {
            width: w,
            height: h,
            depth_or_array_layers: 1,
        },
    );
    let view = texture.create_view(&wgpu::TextureViewDescriptor {
        label: Some("pathtrace-env-view"),
        dimension: Some(wgpu::TextureViewDimension::D2),
        ..Default::default()
    });
    let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
        label: Some("pathtrace-env-sampler"),
        // Equirectangular wraps on φ but clamps on θ — i.e. tile in x,
        // clamp in y. Repeat on x lets a ray pointing past 2π wrap
        // cleanly to 0.
        address_mode_u: wgpu::AddressMode::Repeat,
        address_mode_v: wgpu::AddressMode::ClampToEdge,
        address_mode_w: wgpu::AddressMode::ClampToEdge,
        mag_filter: wgpu::FilterMode::Linear,
        min_filter: wgpu::FilterMode::Linear,
        mipmap_filter: wgpu::MipmapFilterMode::Nearest,
        ..Default::default()
    });

    // Importance-sample data buffer. Layout:
    //   [0..h+1]                          marginal_cdf
    //   [h+1..h+1+h]                      marginal_pdf
    //   [h+1+h..h+1+h + (w+1)*h]          conditional_cdf
    //   [.. + w*h]                        conditional_pdf
    //
    // For the empty stub (1×1) this is just a few floats; for a 2K
    // env map it's ~16 MB. wgpu's default storage-buffer-size limit
    // accepts both.
    let tables = ImportanceTables::build(env);
    let mut data = Vec::<f32>::new();
    data.extend_from_slice(&tables.marginal_cdf);
    data.extend_from_slice(&tables.marginal_pdf);
    data.extend_from_slice(&tables.conditional_cdf);
    data.extend_from_slice(&tables.conditional_pdf);
    let env_data = make_storage_buffer(device, queue, bytemuck::cast_slice(&data), "env-tables");
    // PT-light-vs-env: surface the env's total power. When `env_map`
    // is None, the stub `(1, 1, [0, 0, 0])` env has zero luminance
    // → zero total — `p_env = 0` → Bernoulli pick collapses to
    // always-triangle, matching the no-env behaviour byte-stably.
    let env_total_power = if env_map.is_some() {
        tables.total_power
    } else {
        0.0
    };
    (texture, view, sampler, env_data, env_total_power)
}

/// Wasm32 fallback: no HDR loading dep on wasm, but the bind group
/// layout still needs valid env resources. Hands back a 1×1 black
/// texture + a stub data buffer.
#[cfg(target_arch = "wasm32")]
fn build_environment_resources_empty(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
) -> (
    wgpu::Texture,
    wgpu::TextureView,
    wgpu::Sampler,
    wgpu::Buffer,
    f32,
) {
    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("pathtrace-env-texture-empty"),
        size: wgpu::Extent3d {
            width: 1,
            height: 1,
            depth_or_array_layers: 1,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba16Float,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    // Write a single black RGBA half-float texel so the texture isn't
    // an uninitialised allocation (some validators complain).
    let zero = [0u16; 4];
    queue.write_texture(
        wgpu::TexelCopyTextureInfo {
            texture: &texture,
            mip_level: 0,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        bytemuck::cast_slice(&zero),
        wgpu::TexelCopyBufferLayout {
            offset: 0,
            bytes_per_row: Some(8),
            rows_per_image: Some(1),
        },
        wgpu::Extent3d {
            width: 1,
            height: 1,
            depth_or_array_layers: 1,
        },
    );
    let view = texture.create_view(&wgpu::TextureViewDescriptor {
        label: Some("pathtrace-env-view-empty"),
        dimension: Some(wgpu::TextureViewDimension::D2),
        ..Default::default()
    });
    let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
        label: Some("pathtrace-env-sampler-empty"),
        mag_filter: wgpu::FilterMode::Linear,
        min_filter: wgpu::FilterMode::Linear,
        ..Default::default()
    });
    // 4 bytes of zero — enough for a non-empty storage binding.
    let env_data = make_storage_buffer(device, queue, &[0u8; 4], "env-tables-empty");
    // Wasm builds never bind a real env map; total power is 0.
    (texture, view, sampler, env_data, 0.0)
}

/// Embeds the procedural-cumulus `.qvg` so every scene boots with a
/// usable density grid. The PT-vdb-ingest follow-up will swap this
/// for an asset-loader path that takes the grid file from the scene
/// description rather than the binary.
pub(crate) const CUMULUS_QVG: &[u8] = include_bytes!("../data/grids/cumulus_64.qvg");

/// Builds the cloud-density 3-D texture from a caller-supplied
/// `Grid3D`. `build_scene_buffers` passes in the embedded default;
/// `--cloud-grid PATH` swaps a runtime grid in via
/// `build_scene_buffers_with_grid`.
pub(crate) fn build_cloud_grid_texture_from(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    grid: crate::pathtrace::grid::Grid3D,
) -> (wgpu::Texture, wgpu::TextureView, wgpu::Sampler) {
    let [w, h, d] = grid.dims;
    let size = wgpu::Extent3d {
        width: w,
        height: h,
        depth_or_array_layers: d,
    };
    let tex = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("pathtrace-cloud-grid"),
        size,
        mip_level_count: 1,
        sample_count: 1,
        // R8Unorm is filterable AND linear-encoded — density is a
        // physical quantity, not gamma. R8UnormSrgb would silently
        // gamma-decode the voxels and ruin transmittance.
        dimension: wgpu::TextureDimension::D3,
        format: wgpu::TextureFormat::R8Unorm,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });
    queue.write_texture(
        wgpu::TexelCopyTextureInfo {
            texture: &tex,
            mip_level: 0,
            origin: wgpu::Origin3d::ZERO,
            aspect: wgpu::TextureAspect::All,
        },
        &grid.voxels,
        wgpu::TexelCopyBufferLayout {
            offset: 0,
            bytes_per_row: Some(w),
            rows_per_image: Some(h),
        },
        size,
    );
    let view = tex.create_view(&wgpu::TextureViewDescriptor {
        label: Some("pathtrace-cloud-grid-view"),
        dimension: Some(wgpu::TextureViewDimension::D3),
        ..Default::default()
    });
    let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
        label: Some("pathtrace-cloud-grid-sampler"),
        address_mode_u: wgpu::AddressMode::ClampToEdge,
        address_mode_v: wgpu::AddressMode::ClampToEdge,
        address_mode_w: wgpu::AddressMode::ClampToEdge,
        mag_filter: wgpu::FilterMode::Linear,
        min_filter: wgpu::FilterMode::Linear,
        mipmap_filter: wgpu::MipmapFilterMode::Nearest,
        ..Default::default()
    });
    (tex, view, sampler)
}

/// Builds the path-tracer's base-color texture array + sampler.
/// Always emits at least one layer — when the scene carries no
/// textures, layer 0 is a 1×1 white pixel so the binding stays valid.
/// Mixed-size inputs are not supported in `PT-textures`; the loader
/// asserts uniform dimensions for now.
/// Native: per-layer resize to a common target size using
/// `image::imageops::resize` with the Triangle filter. Cap at
/// 2048 on each axis — most PBR textures top out there, and
/// downscaling rare 4K textures keeps GPU memory + upload time
/// bounded at this first-render stage. Refining mip selection is
/// a follow-up (PT-texture-lod).
#[cfg(not(target_arch = "wasm32"))]
fn resolve_texture_layers(
    textures: &[crate::pathtrace::mesh::TextureImage],
) -> (u32, u32, u32, Vec<Vec<u8>>) {
    const MAX_DIM: u32 = 2048;
    let target_w = textures.iter().map(|t| t.width).max().unwrap().min(MAX_DIM);
    let target_h = textures
        .iter()
        .map(|t| t.height)
        .max()
        .unwrap()
        .min(MAX_DIM);
    let resized: Vec<Vec<u8>> = textures
        .iter()
        .map(|t| {
            if t.width == target_w && t.height == target_h {
                t.rgba.clone()
            } else {
                let img = image::RgbaImage::from_raw(t.width, t.height, t.rgba.clone())
                    .expect("texture rgba length must match width * height * 4");
                let resized = image::imageops::resize(
                    &img,
                    target_w,
                    target_h,
                    image::imageops::FilterType::Triangle,
                );
                resized.into_raw()
            }
        })
        .collect();
    (target_w, target_h, textures.len() as u32, resized)
}

/// Wasm: no `image` crate available. The wasm web pipeline only
/// loads the embedded Cornell scene where texture layers are
/// already uniformly sized — assert that invariant and zero-copy
/// the layers through.
#[cfg(target_arch = "wasm32")]
fn resolve_texture_layers(
    textures: &[crate::pathtrace::mesh::TextureImage],
) -> (u32, u32, u32, Vec<Vec<u8>>) {
    let w = textures[0].width;
    let h = textures[0].height;
    for (i, t) in textures.iter().enumerate() {
        assert!(
            t.width == w && t.height == h,
            "wasm32 texture-array path: layer {i} is {}×{} but layer 0 is {w}×{h}; \
             mixed sizes need the native `image` crate's resize (currently gated \
             cfg(not(target_arch = \"wasm32\")) in Cargo.toml)",
            t.width,
            t.height,
        );
    }
    let layers: Vec<Vec<u8>> = textures.iter().map(|t| t.rgba.clone()).collect();
    (w, h, textures.len() as u32, layers)
}

fn build_texture_array(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    textures: &[crate::pathtrace::mesh::TextureImage],
) -> (wgpu::Texture, wgpu::TextureView, wgpu::Sampler) {
    // Plan 0022 finding: real-world glTF assets (e.g. Sponza) ship
    // textures at mismatched dimensions (4×4 placeholders + 1K and
    // 2K material maps in the same scene). Resize each layer to a
    // common (max-dimensions, capped) target so the texture array
    // can hold them as parallel layers.
    //
    // Native uses `image::imageops::resize`; wasm doesn't carry the
    // `image` crate (it's gated under `cfg(not(target_arch =
    // "wasm32"))` in Cargo.toml so the `hdr` feature stays native-
    // only). The wasm web pipeline only ever loads the embedded
    // Cornell scene where textures are already uniformly sized,
    // so the wasm path keeps the original assert + zero-copy
    // upload.
    let (width, height, layer_count, resized) = if textures.is_empty() {
        (1u32, 1u32, 1u32, Vec::new())
    } else {
        resolve_texture_layers(textures)
    };
    let source: Option<&[Vec<u8>]> = if textures.is_empty() {
        None
    } else {
        Some(&resized)
    };

    let texture = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("pathtrace-textures"),
        size: wgpu::Extent3d {
            width,
            height,
            depth_or_array_layers: layer_count,
        },
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format: wgpu::TextureFormat::Rgba8UnormSrgb,
        usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
        view_formats: &[],
    });

    match source {
        Some(layers) => {
            for (layer_idx, layer_rgba) in layers.iter().enumerate() {
                queue.write_texture(
                    wgpu::TexelCopyTextureInfo {
                        texture: &texture,
                        mip_level: 0,
                        origin: wgpu::Origin3d {
                            x: 0,
                            y: 0,
                            z: layer_idx as u32,
                        },
                        aspect: wgpu::TextureAspect::All,
                    },
                    layer_rgba,
                    wgpu::TexelCopyBufferLayout {
                        offset: 0,
                        bytes_per_row: Some(width * 4),
                        rows_per_image: Some(height),
                    },
                    wgpu::Extent3d {
                        width,
                        height,
                        depth_or_array_layers: 1,
                    },
                );
            }
        }
        None => {
            // 1×1 opaque white default.
            queue.write_texture(
                wgpu::TexelCopyTextureInfo {
                    texture: &texture,
                    mip_level: 0,
                    origin: wgpu::Origin3d::ZERO,
                    aspect: wgpu::TextureAspect::All,
                },
                &[255u8, 255, 255, 255],
                wgpu::TexelCopyBufferLayout {
                    offset: 0,
                    bytes_per_row: Some(4),
                    rows_per_image: Some(1),
                },
                wgpu::Extent3d {
                    width: 1,
                    height: 1,
                    depth_or_array_layers: 1,
                },
            );
        }
    }

    let view = texture.create_view(&wgpu::TextureViewDescriptor {
        label: Some("pathtrace-textures-view"),
        dimension: Some(wgpu::TextureViewDimension::D2Array),
        ..Default::default()
    });

    let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
        label: Some("pathtrace-sampler"),
        address_mode_u: wgpu::AddressMode::Repeat,
        address_mode_v: wgpu::AddressMode::Repeat,
        address_mode_w: wgpu::AddressMode::Repeat,
        mag_filter: wgpu::FilterMode::Linear,
        min_filter: wgpu::FilterMode::Linear,
        mipmap_filter: wgpu::MipmapFilterMode::Nearest,
        ..Default::default()
    });

    (texture, view, sampler)
}

pub(crate) fn build_pathtrace_bg(
    device: &wgpu::Device,
    bgl: &wgpu::BindGroupLayout,
    buffers: &SceneBuffers,
) -> wgpu::BindGroup {
    let _ = &buffers.textures; // hold reference live across the bind group's Arc.
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("pathtrace-bg"),
        layout: bgl,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: buffers.uniform.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: buffers.vertex.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 2,
                resource: buffers.index.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 3,
                resource: buffers.material.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 4,
                resource: buffers.triangle_material.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 5,
                resource: buffers.emissive_triangle.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 6,
                resource: buffers.bvh_nodes.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 7,
                resource: buffers.bvh_tri_indices.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 8,
                resource: wgpu::BindingResource::TextureView(&buffers.textures_view),
            },
            wgpu::BindGroupEntry {
                binding: 9,
                resource: wgpu::BindingResource::Sampler(&buffers.sampler),
            },
            wgpu::BindGroupEntry {
                binding: 10,
                resource: wgpu::BindingResource::TextureView(&buffers.cloud_grid_view),
            },
            wgpu::BindGroupEntry {
                binding: 11,
                resource: wgpu::BindingResource::Sampler(&buffers.cloud_grid_sampler),
            },
            wgpu::BindGroupEntry {
                binding: 12,
                resource: wgpu::BindingResource::TextureView(&buffers.env_view),
            },
            wgpu::BindGroupEntry {
                binding: 13,
                resource: wgpu::BindingResource::Sampler(&buffers.env_sampler),
            },
            wgpu::BindGroupEntry {
                binding: 14,
                resource: buffers.env_data.as_entire_binding(),
            },
        ],
    })
}

pub(crate) fn build_accumulate_bgl(device: &wgpu::Device) -> wgpu::BindGroupLayout {
    let tex = |binding: u32| wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Texture {
            sample_type: wgpu::TextureSampleType::Float { filterable: false },
            view_dimension: wgpu::TextureViewDimension::D2,
            multisampled: false,
        },
        count: None,
    };
    let mut entries: Vec<wgpu::BindGroupLayoutEntry> = Vec::with_capacity(1 + 2 * NUM_AOVS);
    entries.push(wgpu::BindGroupLayoutEntry {
        binding: 0,
        visibility: wgpu::ShaderStages::FRAGMENT,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Uniform,
            has_dynamic_offset: false,
            min_binding_size: None,
        },
        count: None,
    });
    for i in 0..(2 * NUM_AOVS) as u32 {
        entries.push(tex(1 + i));
    }
    device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("accumulate-bgl"),
        entries: &entries,
    })
}

pub(crate) fn make_pipeline(
    device: &wgpu::Device,
    label: &str,
    src: &str,
    bgl: &wgpu::BindGroupLayout,
    formats: &[wgpu::TextureFormat],
) -> wgpu::RenderPipeline {
    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some(label),
        source: wgpu::ShaderSource::Wgsl(src.into()),
    });
    let layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: Some(label),
        bind_group_layouts: &[Some(bgl)],
        immediate_size: 0,
    });
    // `blend: None` (not BlendState::REPLACE) so the same helper works
    // for Rgba32Float, which wgpu rejects as non-blendable even when the
    // semantic is "no blend".
    let targets: Vec<Option<wgpu::ColorTargetState>> = formats
        .iter()
        .map(|f| {
            Some(wgpu::ColorTargetState {
                format: *f,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })
        })
        .collect();
    device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some(label),
        layout: Some(&layout),
        vertex: wgpu::VertexState {
            module: &module,
            entry_point: Some("vs_main"),
            buffers: &[],
            compilation_options: Default::default(),
        },
        fragment: Some(wgpu::FragmentState {
            module: &module,
            entry_point: Some("fs_main"),
            targets: &targets,
            compilation_options: Default::default(),
        }),
        primitive: wgpu::PrimitiveState::default(),
        depth_stencil: None,
        multisample: wgpu::MultisampleState::default(),
        multiview_mask: None,
        cache: None,
    })
}

impl State {
    /// Builds the renderer for an already-created surface of the given size.
    pub async fn new(
        instance: wgpu::Instance,
        surface: wgpu::Surface<'static>,
        width: u32,
        height: u32,
    ) -> State {
        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::default(),
                compatible_surface: Some(&surface),
                force_fallback_adapter: false,
            })
            .await
            .expect("no suitable GPU adapter found (does this browser support WebGPU?)");
        log::info!("adapter: {:?}", adapter.get_info());

        // T1 uses fragment-stage storage buffers (triangle data), which
        // `downlevel_webgl2_defaults()` doesn't grant. WebGPU baseline
        // limits give us 8 storage buffers per shader stage — plenty for
        // the 5 we need. WebGL2 fallback is dropped here; per
        // `AGENTS.md`, WebGPU was the primary target anyway.
        let (device, queue) = adapter
            .request_device(&wgpu::DeviceDescriptor {
                label: Some("quasi-device"),
                required_features: wgpu::Features::empty(),
                required_limits: wgpu::Limits::default(),
                ..Default::default()
            })
            .await
            .expect("failed to create device");

        let surface_caps = surface.get_capabilities(&adapter);
        // A non-sRGB surface: the present shader applies gamma itself.
        let surface_format = surface_caps
            .formats
            .iter()
            .copied()
            .find(|f| !f.is_srgb())
            .unwrap_or(surface_caps.formats[0]);

        let config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format: surface_format,
            width: width.max(1),
            height: height.max(1),
            present_mode: surface_caps.present_modes[0],
            alpha_mode: surface_caps.alpha_modes[0],
            view_formats: vec![],
            desired_maximum_frame_latency: 2,
        };
        surface.configure(&device, &config);

        // --- Bind group layouts ---
        let pathtrace_bgl = build_pathtrace_bgl(&device);
        let accumulate_bgl = build_accumulate_bgl(&device);
        let present_bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("present-bgl"),
            entries: &[wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Texture {
                    sample_type: wgpu::TextureSampleType::Float { filterable: false },
                    view_dimension: wgpu::TextureViewDimension::D2,
                    multisampled: false,
                },
                count: None,
            }],
        });

        // --- Pipelines ---
        let aov_formats = [HDR_FORMAT; NUM_AOVS];
        let pathtrace_pipeline = make_pipeline(
            &device,
            "pathtrace",
            include_str!("pathtrace/shaders/pathtrace.wgsl"),
            &pathtrace_bgl,
            &aov_formats,
        );
        let accumulate_pipeline = make_pipeline(
            &device,
            "accumulate",
            include_str!("pathtrace/shaders/accumulate.wgsl"),
            &accumulate_bgl,
            &aov_formats,
        );
        let present_pipeline = make_pipeline(
            &device,
            "present",
            include_str!("pathtrace/shaders/present.wgsl"),
            &present_bgl,
            &[config.format],
        );

        // --- Triangle scene + scene buffers ---
        let triangle_scene = default_triangle_scene();
        let mut uniforms = scene::Uniforms::zeroed();
        uniforms.triangle_count = triangle_scene.triangle_count() as u32;
        uniforms.emissive_count = triangle_scene.emissive_lights.len() as u32;
        uniforms.sampler_kind = SamplerKind::default().as_u32();
        uniforms.integrator_kind = IntegratorKind::default().as_u32();
        uniforms.use_bvh = 1;
        uniforms.triangle_total_power = triangle_scene.triangle_total_power;

        let scene_buffers = build_scene_buffers(&device, &queue, &triangle_scene);
        let pathtrace_bg = build_pathtrace_bg(&device, &pathtrace_bgl, &scene_buffers);
        let SceneBuffers {
            uniform: uniform_buf,
            vertex: vertex_buf,
            index: index_buf,
            material: material_buf,
            triangle_material: triangle_material_buf,
            emissive_triangle: emissive_triangle_buf,
            bvh_nodes: bvh_nodes_buf,
            bvh_tri_indices: bvh_tri_indices_buf,
            textures: textures_tex,
            textures_view: _,
            sampler: sampler_obj,
            cloud_grid: cloud_grid_tex,
            cloud_grid_view: _,
            cloud_grid_sampler: cloud_grid_sampler_obj,
            env_texture: env_tex,
            env_view: _,
            env_sampler: env_sampler_obj,
            env_data: env_data_buf,
            env_total_power,
        } = scene_buffers;
        uniforms.env_total_power = env_total_power;

        let accum_uniform_buf = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("accum-uniform"),
            size: std::mem::size_of::<AccumUniform>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let targets = build_targets(
            &device,
            config.width,
            config.height,
            &accumulate_bgl,
            &present_bgl,
            &accum_uniform_buf,
        );

        State {
            surface,
            device,
            queue,
            config,
            pathtrace_pipeline,
            accumulate_pipeline,
            present_pipeline,
            accumulate_bgl,
            present_bgl,
            uniform_buf,
            accum_uniform_buf,
            pathtrace_bg,
            _vertex_buf: vertex_buf,
            _index_buf: index_buf,
            _material_buf: material_buf,
            _triangle_material_buf: triangle_material_buf,
            _emissive_triangle_buf: emissive_triangle_buf,
            _bvh_nodes_buf: bvh_nodes_buf,
            _bvh_tri_indices_buf: bvh_tri_indices_buf,
            _textures: textures_tex,
            _sampler: sampler_obj,
            _cloud_grid: cloud_grid_tex,
            _cloud_grid_sampler: cloud_grid_sampler_obj,
            _env_texture: env_tex,
            _env_sampler: env_sampler_obj,
            _env_data: env_data_buf,
            targets,
            uniforms,
            camera: OrbitCamera::new(),
            frame_count: 0,
            read_idx: 0,
        }
    }

    pub fn resize(&mut self, width: u32, height: u32) {
        if width > 0 && height > 0 && (width != self.config.width || height != self.config.height) {
            self.config.width = width;
            self.config.height = height;
            self.surface.configure(&self.device, &self.config);
            self.targets = build_targets(
                &self.device,
                width,
                height,
                &self.accumulate_bgl,
                &self.present_bgl,
                &self.accum_uniform_buf,
            );
            self.frame_count = 0;
            self.read_idx = 0;
        }
    }

    /// Selects the sampler used by the integrator. Restarts accumulation
    /// since the noise statistics change.
    pub fn set_sampler(&mut self, kind: SamplerKind) {
        if self.uniforms.sampler_kind != kind.as_u32() {
            self.uniforms.sampler_kind = kind.as_u32();
            self.frame_count = 0;
            self.read_idx = 0;
        }
    }

    /// Selects the integrator (MIS+NEE vs pure BSDF). Restarts accumulation
    /// since the two integrators converge to the same mean from different
    /// noise distributions.
    pub fn set_integrator(&mut self, kind: IntegratorKind) {
        if self.uniforms.integrator_kind != kind.as_u32() {
            self.uniforms.integrator_kind = kind.as_u32();
            self.frame_count = 0;
            self.read_idx = 0;
        }
    }

    /// Clears the running average so the next rendered frame becomes
    /// sample 0. Used by the web widget's `reset` control.
    pub fn reset_accumulation(&mut self) {
        self.frame_count = 0;
        self.read_idx = 0;
    }

    /// Toggle between BVH traversal (the T2 default) and the linear
    /// scan kept for verification. Accumulation resets because the two
    /// traversals are bit-identical only at infinite spp; the
    /// monte-carlo paths happen to be deterministic given identical
    /// RNG state, but cumulative numerical-precision drift could
    /// matter for tight regressions.
    pub fn set_use_bvh(&mut self, use_bvh: bool) {
        let flag = u32::from(use_bvh);
        if self.uniforms.use_bvh != flag {
            self.uniforms.use_bvh = flag;
            self.frame_count = 0;
            self.read_idx = 0;
        }
    }

    pub fn render(&mut self) {
        let frame = match self.surface.get_current_texture() {
            wgpu::CurrentSurfaceTexture::Success(t)
            | wgpu::CurrentSurfaceTexture::Suboptimal(t) => t,
            wgpu::CurrentSurfaceTexture::Outdated | wgpu::CurrentSurfaceTexture::Lost => {
                self.surface.configure(&self.device, &self.config);
                return;
            }
            wgpu::CurrentSurfaceTexture::Timeout | wgpu::CurrentSurfaceTexture::Occluded => return,
            wgpu::CurrentSurfaceTexture::Validation => {
                log::warn!("surface validation error acquiring frame");
                return;
            }
        };

        // Restart accumulation when the camera moved.
        if self.camera.dirty {
            self.camera.dirty = false;
            self.frame_count = 0;
            self.read_idx = 0;
        }

        let pos = self.camera.position();
        let dir = self.camera.direction();
        self.uniforms.camera.position = pos;
        self.uniforms.camera.direction = dir;
        self.uniforms.camera.up = [0.0, 1.0, 0.0];
        self.uniforms.camera.fov = self.camera.fov;
        self.uniforms.camera.aspect = self.config.width as f32 / self.config.height as f32;
        self.uniforms.frame_count = self.frame_count;
        self.uniforms.viewport_width = self.config.width;
        self.uniforms.viewport_height = self.config.height;
        self.queue
            .write_buffer(&self.uniform_buf, 0, bytemuck::bytes_of(&self.uniforms));
        self.queue.write_buffer(
            &self.accum_uniform_buf,
            0,
            bytemuck::bytes_of(&AccumUniform {
                frame_count: self.frame_count,
                _pad: [0; 3],
            }),
        );

        let src = self.read_idx;
        let dst = 1 - src;
        let surface_view = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("frame-encoder"),
            });

        // 1. Path-trace pass: 4 MRT outputs into sample_views[0..4].
        mrt_pass(
            &mut encoder,
            "pathtrace",
            &self.targets.sample_views,
            |rp| {
                rp.set_pipeline(&self.pathtrace_pipeline);
                rp.set_bind_group(0, &self.pathtrace_bg, &[]);
                rp.draw(0..3, 0..1);
            },
        );
        // 2. Accumulate pass: 4 MRT outputs into accum_views[dst].
        mrt_pass(
            &mut encoder,
            "accumulate",
            &self.targets.accum_views[dst],
            |rp| {
                rp.set_pipeline(&self.accumulate_pipeline);
                rp.set_bind_group(0, &self.targets.accumulate_bg[src], &[]);
                rp.draw(0..3, 0..1);
            },
        );
        // 3. Present (radiance only) to the surface.
        single_attachment_pass(&mut encoder, "present", &surface_view, |rp| {
            rp.set_pipeline(&self.present_pipeline);
            rp.set_bind_group(0, &self.targets.present_bg[dst], &[]);
            rp.draw(0..3, 0..1);
        });

        self.queue.submit(std::iter::once(encoder.finish()));
        frame.present();

        self.read_idx = dst;
        self.frame_count += 1;
    }
}

/// One render pass into a single color attachment.
pub(crate) fn single_attachment_pass<F: FnOnce(&mut wgpu::RenderPass)>(
    encoder: &mut wgpu::CommandEncoder,
    label: &str,
    target: &wgpu::TextureView,
    draw: F,
) {
    let mut rp = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
        label: Some(label),
        color_attachments: &[Some(wgpu::RenderPassColorAttachment {
            view: target,
            depth_slice: None,
            resolve_target: None,
            ops: wgpu::Operations {
                load: wgpu::LoadOp::Clear(wgpu::Color::BLACK),
                store: wgpu::StoreOp::Store,
            },
        })],
        depth_stencil_attachment: None,
        timestamp_writes: None,
        occlusion_query_set: None,
        multiview_mask: None,
    });
    draw(&mut rp);
}

/// One render pass into the four AOV color attachments.
pub(crate) fn mrt_pass<F: FnOnce(&mut wgpu::RenderPass)>(
    encoder: &mut wgpu::CommandEncoder,
    label: &str,
    targets: &[wgpu::TextureView; NUM_AOVS],
    draw: F,
) {
    let atts: [Option<wgpu::RenderPassColorAttachment>; NUM_AOVS] = std::array::from_fn(|i| {
        Some(wgpu::RenderPassColorAttachment {
            view: &targets[i],
            depth_slice: None,
            resolve_target: None,
            ops: wgpu::Operations {
                load: wgpu::LoadOp::Clear(wgpu::Color::BLACK),
                store: wgpu::StoreOp::Store,
            },
        })
    });
    let mut rp = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
        label: Some(label),
        color_attachments: &atts,
        depth_stencil_attachment: None,
        timestamp_writes: None,
        occlusion_query_set: None,
        multiview_mask: None,
    });
    draw(&mut rp);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accum_uniform_is_16_bytes() {
        assert_eq!(std::mem::size_of::<AccumUniform>(), 16);
    }

    #[test]
    fn aov_indices_are_distinct_and_packed() {
        // The order matters: shader `@location(N)` must match the array
        // index used in mrt_pass and the present bind group.
        assert_eq!(AOV_RADIANCE, 0);
        assert_eq!(AOV_ALBEDO, 1);
        assert_eq!(AOV_NORMAL, 2);
        assert_eq!(AOV_DEPTH, 3);
        assert_eq!(NUM_AOVS, 4);
    }
}
